# Default values for spark-hs
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bitnami/spark
  tag: 3.0.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
#  - name: my-secret

serviceAccount:
  create: false
  name: "sa-with-s3-access"

# -- S3 path to read logs from
S3logPath: "my-company-s3-bucket/spark-hs"

spark:
  credProviderString: ""
  maxFilesToRetain: ""

service:
  externalPort: 80
  internalPort: 18080
  type: ClusterIP

resources: {}
# resources:
#   limits:
#     cpu: 500m
#     memory: 1024Mi

#   requests:
#     cpu: 250m
#     memory: 512Mi

ingress:
  enabled: false
  host: "spark.example.io"

tolerations: []
affinity: {}
