apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark-hs.fullname" . }}
  labels:
    {{- include "spark-hs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Chart.Name }}
  selector:
    {{- include "spark-hs.selectorLabels" . | nindent 6 }}
