kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "spark-hs.fullname" . }}-spark-hs-config
data:
  spark-defaults.conf: |-
    spark.hadoop.fs.s3a.aws.credentials.provider={{ .Values.spark.credProviderString }}
    spark.history.fs.eventLog.rolling.maxFilesToRetain={{ .Values.spark.maxFilesToRetain }}
